use std::collections::HashSet;
use std::time::Duration;

use anyhow::Result;
use teloxide::prelude::*;
use teloxide::types::{
    ChatAction, FileId, InlineKeyboardButton, InlineKeyboardMarkup, InputFile, InputMedia,
    InputMediaPhoto, MessageId, ParseMode, ReplyParameters,
};

use crate::config::{CONFIG, TLDR_SYSTEM_PROMPT};
use crate::handlers::access::{check_access_control, is_rate_limited};
pub(crate) use crate::handlers::admin::{diagnose_handler, status_handler};
use crate::handlers::content::{
    create_telegraph_page, extract_telegraph_urls_and_content, extract_twitter_urls_and_content,
};
pub(crate) use crate::handlers::factcheck::factcheck_handler;
pub(crate) use crate::handlers::help::{help_handler, start_handler, support_handler};
use crate::handlers::media::{get_file_url, message_has_image};
pub(crate) use crate::handlers::mysong::mysong_handler;
pub(crate) use crate::handlers::persona::{paintme_handler, profileme_handler};
use crate::handlers::responses::send_response;
pub(crate) use crate::handlers::token_stats::{
    burn_baby_burn_handler, token_devourers_handler, token_stats_handler,
};
use crate::llm::audit::create_command_audit_context;
use crate::llm::gemini::ImageGenerationError;
use crate::llm::media::detect_mime_type;
use crate::llm::text_model::call_configured_text_model;
use crate::llm::{
    audit_context_from_id, generate_image_with_codex, generate_image_with_gemini,
    generate_image_with_img2, generate_video_with_veo, CodexImageConfig, GeminiImageConfig,
    LlmAuditContext,
};
use crate::state::{AppState, ImageGenerationModel, PendingImageCommand, PendingImageRequest};
use crate::tools::cwd_uploader::upload_image_bytes_to_cwd;
use crate::utils::markdown::markdown_to_telegram_html;
use crate::utils::progress::ProgressReporter;
use crate::utils::telegram::{
    edit_message_text_with_retry, message_entities_for_text, retry_telegram,
    send_message_with_retry, start_chat_action_heartbeat, strip_command_prefix,
};
use crate::utils::text::{escape_html, truncate_with_ellipsis};
use crate::utils::timing::{complete_command_timer, start_command_timer};
use tracing::{error, info, warn};

const IMAGE_RESOLUTION_OPTIONS: [&str; 3] = ["2K", "4K", "1K"];
const IMAGE_ASPECT_RATIO_OPTIONS: [&str; 14] = [
    "4:3", "3:4", "16:9", "9:16", "1:1", "21:9", "3:2", "2:3", "5:4", "4:5", "4:1", "1:4", "8:1",
    "1:8",
];
pub const IMAGE_RESOLUTION_CALLBACK_PREFIX: &str = "image_res:";
pub const IMAGE_ASPECT_RATIO_CALLBACK_PREFIX: &str = "image_aspect:";
pub const IMAGE_MODEL_CALLBACK_PREFIX: &str = "image_model:";
pub const IMAGE_CODEX_SIZE_CALLBACK_PREFIX: &str = "image_codex_size:";
const IMAGE_DEFAULT_RESOLUTION: &str = "2K";
const IMAGE_ASPECT_RATIO_AUTO_CALLBACK: &str = "auto";
pub(super) const IMAGE_CAPTION_LIMIT: usize = 1000;
const IMAGE_CAPTION_PROMPT_PREVIEW: usize = 900;
#[derive(Debug, Clone)]
struct ImageRequestContext {
    prompt: String,
    image_urls: Vec<String>,
    telegraph_contents: Vec<String>,
}

pub(super) async fn build_image_caption(model_name: &str, prompt: &str) -> String {
    let safe_model = escape_html(model_name);
    let base_caption = format!("Generated by {}", safe_model);
    let clean_prompt = if prompt.trim().is_empty() {
        "No prompt provided."
    } else {
        prompt
    };
    let escaped_prompt = escape_html(clean_prompt);
    let mut caption = format!(
        "{} with prompt:\n<pre>{}</pre>",
        base_caption, escaped_prompt
    );
    if caption.chars().count() <= IMAGE_CAPTION_LIMIT {
        return caption;
    }

    if let Some(url) = create_telegraph_page("Image Generation Prompt", clean_prompt).await {
        caption = format!(
            "{} with prompt:\n<a href=\"{}\">View it here</a>",
            base_caption,
            escape_html(&url)
        );
        if caption.chars().count() <= IMAGE_CAPTION_LIMIT {
            return caption;
        }
    }

    let prompt_preview = truncate_with_ellipsis(clean_prompt, IMAGE_CAPTION_PROMPT_PREVIEW);
    caption = format!(
        "{} with prompt:\n<pre>{}</pre>",
        base_caption,
        escape_html(&prompt_preview)
    );
    if caption.chars().count() <= IMAGE_CAPTION_LIMIT {
        caption
    } else {
        base_caption
    }
}

fn build_img2_spoiler_caption(caption: &str) -> String {
    format!("<tg-spoiler>{}</tg-spoiler>", caption)
}

fn build_img2_spoiler_photo_media(input_file: InputFile, caption: &str) -> InputMedia {
    InputMedia::Photo(
        InputMediaPhoto::new(input_file)
            .caption(build_img2_spoiler_caption(caption))
            .parse_mode(ParseMode::Html)
            .spoiler(),
    )
}

async fn send_video_with_retry(
    bot: &Bot,
    chat_id: ChatId,
    video_bytes: &[u8],
    reply_to: Option<MessageId>,
) -> Result<Message> {
    retry_telegram("send_video", || {
        let input = InputFile::memory(video_bytes.to_vec()).file_name("video.mp4");
        let mut request = bot.send_video(chat_id, input);
        if let Some(reply_to) = reply_to {
            request = request.reply_parameters(ReplyParameters::new(reply_to));
        }
        request
    })
    .await
    .map_err(Into::into)
}

async fn prepare_image_request(
    bot: &Bot,
    state: &AppState,
    message: &Message,
    command_prefix: &str,
) -> Result<ImageRequestContext> {
    let original_message_text = message
        .text()
        .map(|value| value.to_string())
        .or_else(|| message.caption().map(|value| value.to_string()))
        .unwrap_or_default();

    let prompt_raw = strip_command_prefix(&original_message_text, command_prefix);
    let mut image_urls = Vec::new();
    let mut seen_file_ids: HashSet<FileId> = HashSet::new();
    let mut telegraph_texts = Vec::new();
    let prompt_entities = message_entities_for_text(message);

    if let Some(media_group_id) = message.media_group_id() {
        let group_items = state.media_group_items(media_group_id);
        for item in group_items {
            if seen_file_ids.insert(item.file_id.clone()) {
                if let Ok(url) = get_file_url(bot, &item.file_id).await {
                    image_urls.push(url);
                }
            }
        }
    }

    if let Some(photo_sizes) = message.photo() {
        if let Some(photo) = photo_sizes.last() {
            if seen_file_ids.insert(photo.file.id.clone()) {
                if let Ok(url) = get_file_url(bot, &photo.file.id).await {
                    image_urls.push(url);
                }
            }
        }
    }

    let (prompt, telegraph_contents) =
        extract_telegraph_urls_and_content(&prompt_raw, prompt_entities.as_deref(), 5).await;
    let (mut prompt, twitter_contents) =
        extract_twitter_urls_and_content(&prompt, prompt_entities.as_deref(), 5).await;
    telegraph_texts.extend(
        telegraph_contents
            .iter()
            .map(|content| content.text_content.clone()),
    );
    telegraph_texts.extend(
        twitter_contents
            .iter()
            .map(|content| content.text_content.clone()),
    );

    if let Some(reply) = message.reply_to_message() {
        let reply_has_images = message_has_image(reply);
        if let Some(media_group_id) = reply.media_group_id() {
            let group_items = state.media_group_items(media_group_id);
            for item in group_items {
                if seen_file_ids.insert(item.file_id.clone()) {
                    if let Ok(url) = get_file_url(bot, &item.file_id).await {
                        image_urls.push(url);
                    }
                }
            }
        }

        if image_urls.is_empty() {
            if let Some(photo_sizes) = reply.photo() {
                if let Some(photo) = photo_sizes.last() {
                    if seen_file_ids.insert(photo.file.id.clone()) {
                        if let Ok(url) = get_file_url(bot, &photo.file.id).await {
                            image_urls.push(url);
                        }
                    }
                }
            }
        }

        let reply_text = reply
            .text()
            .map(|value| value.to_string())
            .or_else(|| reply.caption().map(|value| value.to_string()))
            .unwrap_or_default();
        if !reply_text.trim().is_empty() && !reply_has_images {
            let reply_entities = message_entities_for_text(reply);
            let (reply_text, reply_telegraph) =
                extract_telegraph_urls_and_content(&reply_text, reply_entities.as_deref(), 5).await;
            let (reply_text, reply_twitter) =
                extract_twitter_urls_and_content(&reply_text, reply_entities.as_deref(), 5).await;
            telegraph_texts.extend(
                reply_telegraph
                    .iter()
                    .map(|content| content.text_content.clone()),
            );
            telegraph_texts.extend(
                reply_twitter
                    .iter()
                    .map(|content| content.text_content.clone()),
            );

            if prompt.trim().is_empty() {
                prompt = reply_text;
            } else {
                prompt = format!("{}\n\n{}", reply_text, prompt);
            }
        }
    }

    Ok(ImageRequestContext {
        prompt,
        image_urls,
        telegraph_contents: telegraph_texts,
    })
}

fn build_resolution_keyboard(request_key: &str) -> InlineKeyboardMarkup {
    let buttons = IMAGE_RESOLUTION_OPTIONS
        .iter()
        .map(|res| {
            InlineKeyboardButton::callback(
                res.to_string(),
                format!(
                    "{}{}|{}",
                    IMAGE_RESOLUTION_CALLBACK_PREFIX, request_key, res
                ),
            )
        })
        .collect::<Vec<_>>();

    let rows = buttons
        .chunks(3)
        .map(|chunk| chunk.to_vec())
        .collect::<Vec<_>>();
    InlineKeyboardMarkup::new(rows)
}

fn image_model_callback_data(request_key: &str, model: ImageGenerationModel) -> String {
    let token = match model {
        ImageGenerationModel::Gemini => "gemini",
        ImageGenerationModel::CodexGptImage2 => "codex",
    };
    format!("{}{}|{}", IMAGE_MODEL_CALLBACK_PREFIX, request_key, token)
}

fn parse_image_generation_model(value: &str) -> Option<ImageGenerationModel> {
    match value.trim() {
        "gemini" => Some(ImageGenerationModel::Gemini),
        "codex" => Some(ImageGenerationModel::CodexGptImage2),
        _ => None,
    }
}

fn parse_default_image_generation_model(value: &str) -> Option<ImageGenerationModel> {
    match value.trim().to_lowercase().as_str() {
        "gemini" => Some(ImageGenerationModel::Gemini),
        "codex" | "openai-codex" | "openai-codex:selected" => {
            Some(ImageGenerationModel::CodexGptImage2)
        }
        _ => None,
    }
}

fn resolve_default_image_generation_model(
    default_model: &str,
    gemini_available: bool,
    codex_available: bool,
) -> std::result::Result<ImageGenerationModel, String> {
    let Some(model) = parse_default_image_generation_model(default_model) else {
        return Err(format!(
            "Default image model {} is not supported. Set DEFAULT_IMAGE_MODEL to gemini or codex.",
            default_model.trim()
        ));
    };

    if model == ImageGenerationModel::Gemini && !gemini_available {
        if codex_available {
            return Ok(ImageGenerationModel::CodexGptImage2);
        }
        return Err(
            "No image model is configured. Enable Gemini or complete Codex setup with /codexlogin."
                .to_string(),
        );
    }

    if model == ImageGenerationModel::CodexGptImage2 && !codex_available {
        return Err(format!(
            "Default image model {} is unavailable. Complete Codex setup with /codexlogin or set DEFAULT_IMAGE_MODEL=gemini.",
            default_model.trim()
        ));
    }

    Ok(model)
}

pub(super) async fn generate_image_with_configured_default(
    prompt: &str,
    image_urls: &[String],
    gemini_config: Option<GeminiImageConfig>,
    codex_config: Option<CodexImageConfig>,
    upload_to_cwd: bool,
    audit_context: Option<&LlmAuditContext>,
) -> (
    String,
    std::result::Result<Vec<Vec<u8>>, ImageGenerationError>,
) {
    let model = match resolve_default_image_generation_model(
        &CONFIG.default_image_model,
        CONFIG.gemini_api_available(),
        crate::llm::codex_image::codex_image_available(),
    ) {
        Ok(model) => model,
        Err(err) => {
            return (
                CONFIG.default_image_model.clone(),
                Err(ImageGenerationError(err)),
            );
        }
    };

    match model {
        ImageGenerationModel::Gemini => (
            CONFIG.gemini_image_model.clone(),
            generate_image_with_gemini(
                prompt,
                image_urls,
                gemini_config,
                upload_to_cwd,
                audit_context,
            )
            .await,
        ),
        ImageGenerationModel::CodexGptImage2 => {
            let model_name = crate::llm::codex_image::codex_image_display_model();
            (
                model_name,
                generate_image_with_codex(
                    prompt,
                    image_urls,
                    codex_config,
                    upload_to_cwd,
                    audit_context,
                )
                .await,
            )
        }
    }
}

fn build_image_model_keyboard(
    request_key: &str,
    include_gemini: bool,
    include_codex: bool,
    default_model: ImageGenerationModel,
) -> InlineKeyboardMarkup {
    let mut buttons = Vec::new();
    if include_gemini {
        buttons.push(InlineKeyboardButton::callback(
            CONFIG.gemini_image_model.clone(),
            image_model_callback_data(request_key, ImageGenerationModel::Gemini),
        ));
    }

    if include_codex {
        buttons.push(InlineKeyboardButton::callback(
            crate::llm::codex_image::codex_image_display_model(),
            image_model_callback_data(request_key, ImageGenerationModel::CodexGptImage2),
        ));
    }

    if let Some(default_index) = buttons.iter().position(|button| match default_model {
        ImageGenerationModel::Gemini => {
            matches!(
                &button.kind,
                teloxide::types::InlineKeyboardButtonKind::CallbackData(data)
                    if data == &image_model_callback_data(request_key, ImageGenerationModel::Gemini)
            )
        }
        ImageGenerationModel::CodexGptImage2 => {
            matches!(
                &button.kind,
                teloxide::types::InlineKeyboardButtonKind::CallbackData(data)
                    if data == &image_model_callback_data(request_key, ImageGenerationModel::CodexGptImage2)
            )
        }
    }) {
        let default_button = buttons.remove(default_index);
        buttons.insert(0, default_button);
    }

    InlineKeyboardMarkup::new(vec![buttons])
}

fn build_aspect_ratio_keyboard(request_key: &str) -> InlineKeyboardMarkup {
    let mut buttons = vec![InlineKeyboardButton::callback(
        "Auto",
        format!(
            "{}{}|{}",
            IMAGE_ASPECT_RATIO_CALLBACK_PREFIX, request_key, IMAGE_ASPECT_RATIO_AUTO_CALLBACK
        ),
    )];
    buttons.extend(
        IMAGE_ASPECT_RATIO_OPTIONS
            .iter()
            .map(|aspect| {
                InlineKeyboardButton::callback(
                    aspect.to_string(),
                    format!(
                        "{}{}|{}",
                        IMAGE_ASPECT_RATIO_CALLBACK_PREFIX, request_key, aspect
                    ),
                )
            })
            .collect::<Vec<_>>(),
    );

    let rows = buttons
        .chunks(3)
        .map(|chunk| chunk.to_vec())
        .collect::<Vec<_>>();
    InlineKeyboardMarkup::new(rows)
}

fn build_codex_size_keyboard(request_key: &str) -> InlineKeyboardMarkup {
    let buttons = crate::llm::codex_image::CODEX_IMAGE_SUPPORTED_SIZES
        .iter()
        .map(|size| {
            InlineKeyboardButton::callback(
                size.to_string(),
                format!(
                    "{}{}|{}",
                    IMAGE_CODEX_SIZE_CALLBACK_PREFIX, request_key, size
                ),
            )
        })
        .collect::<Vec<_>>();

    let rows = buttons
        .chunks(3)
        .map(|chunk| chunk.to_vec())
        .collect::<Vec<_>>();
    InlineKeyboardMarkup::new(rows)
}

fn resolve_image_request_settings(
    request: &PendingImageRequest,
    resolution: Option<&str>,
    aspect_ratio: Option<&str>,
) -> (String, Option<String>) {
    let final_resolution = resolution
        .or(request.resolution.as_deref())
        .unwrap_or(IMAGE_DEFAULT_RESOLUTION)
        .to_string();
    let final_aspect = aspect_ratio
        .filter(|value| *value != IMAGE_ASPECT_RATIO_AUTO_CALLBACK && !value.trim().is_empty())
        .or(request.aspect_ratio.as_deref())
        .filter(|value| *value != IMAGE_ASPECT_RATIO_AUTO_CALLBACK && !value.trim().is_empty())
        .map(|value| value.to_string());

    (final_resolution, final_aspect)
}

async fn finalize_image_request(
    bot: &Bot,
    state: &AppState,
    request: PendingImageRequest,
    resolution: Option<&str>,
    aspect_ratio: Option<&str>,
) -> Result<()> {
    let _heavy_permit = state.acquire_heavy_command_permit().await;
    let audit_context = audit_context_from_id(&state.db, request.llm_invocation_id);
    let selected_model = match request.model {
        Some(model) => model,
        None => match resolve_default_image_generation_model(
            &CONFIG.default_image_model,
            CONFIG.gemini_api_available(),
            crate::llm::codex_image::codex_image_available(),
        ) {
            Ok(model) => model,
            Err(err) => {
                let _ = bot
                    .edit_message_text(
                        ChatId(request.chat_id),
                        MessageId(request.selection_message_id as i32),
                        err,
                    )
                    .await;
                return Ok(());
            }
        },
    };
    if selected_model == ImageGenerationModel::Gemini && !CONFIG.gemini_api_available() {
        let _ = bot
            .edit_message_text(
                ChatId(request.chat_id),
                MessageId(request.selection_message_id as i32),
                "Gemini image generation is disabled. Please choose another image model.",
            )
            .await;
        return Ok(());
    }
    if selected_model == ImageGenerationModel::CodexGptImage2
        && !crate::llm::codex_image::codex_image_available()
    {
        let _ = bot
            .edit_message_text(
                ChatId(request.chat_id),
                MessageId(request.selection_message_id as i32),
                "Codex image generation is unavailable. Complete Codex setup with /codexlogin.",
            )
            .await;
        return Ok(());
    }

    let mut prompt = request.prompt.clone();
    if !request.telegraph_contents.is_empty() {
        prompt.push_str("\n\nAdditional context:\n");
        for content in &request.telegraph_contents {
            prompt.push_str(content);
            prompt.push('\n');
        }
    }

    let processing_message_id = MessageId(request.selection_message_id as i32);
    let _chat_action = start_chat_action_heartbeat(
        bot.clone(),
        ChatId(request.chat_id),
        ChatAction::UploadPhoto,
    );

    let (model_name, image_result) = match selected_model {
        ImageGenerationModel::Gemini => {
            let (final_resolution, final_aspect) =
                resolve_image_request_settings(&request, resolution, aspect_ratio);
            let image_config = Some(GeminiImageConfig {
                aspect_ratio: final_aspect.clone(),
                image_size: if final_resolution.trim().is_empty() {
                    None
                } else {
                    Some(final_resolution.clone())
                },
            });
            bot.edit_message_text(
                ChatId(request.chat_id),
                processing_message_id,
                if let Some(final_aspect) = final_aspect.as_deref() {
                    format!(
                        "Generating your image with {} at {} resolution with {} aspect ratio...",
                        CONFIG.gemini_image_model, final_resolution, final_aspect
                    )
                } else {
                    format!(
                        "Generating your image with {} at {} resolution with automatic aspect ratio...",
                        CONFIG.gemini_image_model, final_resolution
                    )
                },
            )
            .await?;
            (
                CONFIG.gemini_image_model.clone(),
                generate_image_with_gemini(
                    &prompt,
                    &request.image_urls,
                    image_config,
                    !CONFIG.cwd_pw_api_key.is_empty(),
                    audit_context.as_ref(),
                )
                .await,
            )
        }
        ImageGenerationModel::CodexGptImage2 => {
            let size = request
                .codex_size
                .as_deref()
                .filter(|size| crate::llm::codex_image::is_supported_codex_image_size(size))
                .map(|size| size.to_string());
            let model_name = crate::llm::codex_image::codex_image_display_model();
            bot.edit_message_text(
                ChatId(request.chat_id),
                processing_message_id,
                if let Some(size) = size.as_deref() {
                    format!("Generating your image with {} at {}...", model_name, size)
                } else {
                    format!("Generating your image with {}...", model_name)
                },
            )
            .await?;
            (
                model_name,
                generate_image_with_codex(
                    &prompt,
                    &request.image_urls,
                    Some(CodexImageConfig { size }),
                    !CONFIG.cwd_pw_api_key.is_empty(),
                    audit_context.as_ref(),
                )
                .await,
            )
        }
    };

    let images = match image_result {
        Ok(images) => images,
        Err(err) => {
            error!(
                model = model_name.as_str(),
                "Image generation failed: {}", err.0
            );
            let error_text = format!(
                "Sorry, I couldn't generate the image using {}.\n\nError: {}",
                model_name, err.0
            );
            let _ = bot
                .edit_message_text(ChatId(request.chat_id), processing_message_id, error_text)
                .await;
            return Ok(());
        }
    };
    let caption = build_image_caption(&model_name, &prompt).await;

    let mut image_iter = images.into_iter();
    if let Some(first_image) = image_iter.next() {
        let media = InputMedia::Photo(
            InputMediaPhoto::new(InputFile::memory(first_image.clone()))
                .caption(caption.clone())
                .parse_mode(ParseMode::Html),
        );
        let edit_result = bot
            .edit_message_media(ChatId(request.chat_id), processing_message_id, media)
            .await;
        if edit_result.is_err() {
            bot.send_photo(ChatId(request.chat_id), InputFile::memory(first_image))
                .reply_parameters(ReplyParameters::new(MessageId(request.message_id as i32)))
                .caption(caption)
                .parse_mode(ParseMode::Html)
                .await?;
        }
    }

    for image in image_iter {
        bot.send_photo(ChatId(request.chat_id), InputFile::memory(image))
            .reply_parameters(ReplyParameters::new(MessageId(request.message_id as i32)))
            .await?;
    }

    Ok(())
}

pub async fn image_selection_callback(
    bot: Bot,
    state: AppState,
    query: CallbackQuery,
) -> Result<()> {
    let _ = bot.answer_callback_query(query.id.clone()).await;
    let Some(data) = &query.data else {
        return Ok(());
    };
    let query_user_id = i64::try_from(query.from.id.0).unwrap_or_default();

    if data.starts_with(IMAGE_MODEL_CALLBACK_PREFIX) {
        let payload = data.trim_start_matches(IMAGE_MODEL_CALLBACK_PREFIX);
        let mut parts = payload.split('|');
        let request_key = parts.next().unwrap_or("");
        let model_token = parts.next().unwrap_or("");
        let Some(model) = parse_image_generation_model(model_token) else {
            return Ok(());
        };
        if model == ImageGenerationModel::Gemini && !CONFIG.gemini_api_available() {
            return Ok(());
        }
        if model == ImageGenerationModel::CodexGptImage2
            && !crate::llm::codex_image::codex_image_available()
        {
            return Ok(());
        }

        let (next_command, ready_request) = {
            let mut entry = state.pending_image_requests.entry(request_key);
            let Some(request) = entry.get_mut() else {
                return Ok(());
            };
            if request.user_id != query_user_id {
                return Ok(());
            }
            request.model = Some(model);
            let command = request.command;
            // /img has nothing more to ask: take the request now so the
            // timeout task can no longer race this selection.
            let ready_request = match command {
                PendingImageCommand::Img => entry.take(),
                PendingImageCommand::Image => None,
            };
            (command, ready_request)
        };

        match (next_command, model) {
            (PendingImageCommand::Img, _) => {
                if let Some(request) = ready_request {
                    finalize_image_request(&bot, &state, request, None, None).await?;
                }
            }
            (PendingImageCommand::Image, ImageGenerationModel::Gemini) => {
                if let Some(message) = &query.message {
                    bot.edit_message_text(
                        message.chat().id,
                        message.id(),
                        format!(
                            "Choose a resolution for {} (default: {}).",
                            CONFIG.gemini_image_model, IMAGE_DEFAULT_RESOLUTION
                        ),
                    )
                    .reply_markup(build_resolution_keyboard(request_key))
                    .await?;
                }
            }
            (PendingImageCommand::Image, ImageGenerationModel::CodexGptImage2) => {
                if let Some(message) = &query.message {
                    bot.edit_message_text(
                        message.chat().id,
                        message.id(),
                        format!(
                            "Choose a size for {}, or wait to let the model decide.",
                            crate::llm::codex_image::codex_image_display_model()
                        ),
                    )
                    .reply_markup(build_codex_size_keyboard(request_key))
                    .await?;
                }
            }
        }
        return Ok(());
    }

    if data.starts_with(IMAGE_CODEX_SIZE_CALLBACK_PREFIX) {
        let payload = data.trim_start_matches(IMAGE_CODEX_SIZE_CALLBACK_PREFIX);
        let mut parts = payload.split('|');
        let request_key = parts.next().unwrap_or("");
        let size = parts.next().unwrap_or("");
        if !crate::llm::codex_image::is_supported_codex_image_size(size) {
            return Ok(());
        }

        let ready_request = {
            let mut entry = state.pending_image_requests.entry(request_key);
            match entry.get_mut() {
                Some(request) if request.user_id != query_user_id => return Ok(()),
                Some(request) => {
                    request.model = Some(ImageGenerationModel::CodexGptImage2);
                    request.codex_size = Some(size.to_string());
                }
                None => {}
            }
            entry.take()
        };
        if let Some(request) = ready_request {
            finalize_image_request(&bot, &state, request, None, None).await?;
        }
        return Ok(());
    }

    if data.starts_with(IMAGE_RESOLUTION_CALLBACK_PREFIX) {
        let payload = data.trim_start_matches(IMAGE_RESOLUTION_CALLBACK_PREFIX);
        let mut parts = payload.split('|');
        let request_key = parts.next().unwrap_or("");
        let resolution = parts.next().unwrap_or("");
        if !IMAGE_RESOLUTION_OPTIONS.contains(&resolution) {
            return Ok(());
        }

        if let Some(request) = state.pending_image_requests.entry(request_key).get_mut() {
            if request.user_id != query_user_id {
                return Ok(());
            }
            request.resolution = Some(resolution.to_string());
        }

        if let Some(message) = &query.message {
            bot.edit_message_text(
                message.chat().id,
                message.id(),
                format!(
                    "Resolution set to {}. Choose an aspect ratio, or Auto to let the model decide.",
                    resolution
                ),
            )
            .reply_markup(build_aspect_ratio_keyboard(request_key))
            .await?;
        }
        return Ok(());
    }

    if data.starts_with(IMAGE_ASPECT_RATIO_CALLBACK_PREFIX) {
        let payload = data.trim_start_matches(IMAGE_ASPECT_RATIO_CALLBACK_PREFIX);
        let mut parts = payload.split('|');
        let request_key = parts.next().unwrap_or("");
        let aspect = parts.next().unwrap_or("");
        if aspect != IMAGE_ASPECT_RATIO_AUTO_CALLBACK
            && !IMAGE_ASPECT_RATIO_OPTIONS.contains(&aspect)
        {
            return Ok(());
        }

        let ready_request = {
            let mut entry = state.pending_image_requests.entry(request_key);
            match entry.get_mut() {
                Some(request) if request.user_id != query_user_id => return Ok(()),
                Some(request) => {
                    request.aspect_ratio = if aspect == IMAGE_ASPECT_RATIO_AUTO_CALLBACK {
                        None
                    } else {
                        Some(aspect.to_string())
                    };
                }
                None => {}
            }
            entry.take()
        };

        let selected_aspect = if aspect == IMAGE_ASPECT_RATIO_AUTO_CALLBACK {
            None
        } else {
            Some(aspect)
        };
        if let Some(request) = ready_request {
            finalize_image_request(&bot, &state, request, None, selected_aspect).await?;
        }
    }

    Ok(())
}

pub async fn img_handler(
    bot: Bot,
    state: AppState,
    message: Message,
    _prompt: Option<String>,
) -> Result<()> {
    if !check_access_control(&bot, &message, "img").await {
        return Ok(());
    }
    let user_id = message
        .from
        .as_ref()
        .and_then(|user| i64::try_from(user.id.0).ok())
        .unwrap_or_default();
    if is_rate_limited(user_id) {
        bot.send_message(
            message.chat.id,
            "Rate limit exceeded. Please try again later.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }

    let context = prepare_image_request(&bot, &state, &message, "/img").await?;
    if context.prompt.trim().is_empty() && context.image_urls.is_empty() {
        bot.send_message(
            message.chat.id,
            "Please provide a prompt or reply to an image.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }

    let gemini_available = CONFIG.gemini_api_available();
    let codex_available = crate::llm::codex_image::codex_image_available();
    if !gemini_available && !codex_available {
        bot.send_message(
            message.chat.id,
            "No image model is configured. Enable Gemini or complete Codex setup with /codexlogin.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }

    let default_image_model = match resolve_default_image_generation_model(
        &CONFIG.default_image_model,
        gemini_available,
        codex_available,
    ) {
        Ok(model) => model,
        Err(_) if gemini_available => ImageGenerationModel::Gemini,
        Err(_) => ImageGenerationModel::CodexGptImage2,
    };

    if gemini_available && codex_available {
        let audit_context = create_command_audit_context(&state, &message, "img").await;
        let request_key = format!("{}_{}", message.chat.id.0, message.id.0);
        let selection_message = bot
            .send_message(message.chat.id, "Choose an image model:")
            .reply_parameters(ReplyParameters::new(message.id))
            .reply_markup(build_image_model_keyboard(
                &request_key,
                true,
                true,
                default_image_model,
            ))
            .await?;
        let pending = PendingImageRequest {
            user_id,
            chat_id: message.chat.id.0,
            message_id: message.id.0 as i64,
            command: PendingImageCommand::Img,
            prompt: context.prompt,
            image_urls: context.image_urls,
            telegraph_contents: context.telegraph_contents,
            selection_message_id: selection_message.id.0 as i64,
            llm_invocation_id: audit_context.as_ref().map(|context| context.invocation_id),
            model: None,
            codex_size: None,
            resolution: None,
            aspect_ratio: None,
        };
        let timeout_bot = bot.clone();
        let timeout_state = state.clone();
        state.pending_image_requests.insert_with_timeout(
            request_key,
            pending,
            Duration::from_secs(CONFIG.model_selection_timeout),
            move |request| async move {
                let _ =
                    finalize_image_request(&timeout_bot, &timeout_state, request, None, None).await;
            },
        );
        return Ok(());
    }

    let _heavy_permit = state.acquire_heavy_command_permit().await;
    let audit_context = create_command_audit_context(&state, &message, "img").await;

    let processing_message = bot
        .send_message(message.chat.id, "Generating your image...")
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;

    let mut prompt_text = context.prompt.clone();
    if !context.telegraph_contents.is_empty() {
        prompt_text.push_str("\n\nAdditional context:\n");
        for content in &context.telegraph_contents {
            prompt_text.push_str(content);
            prompt_text.push('\n');
        }
    }
    let _chat_action =
        start_chat_action_heartbeat(bot.clone(), message.chat.id, ChatAction::UploadPhoto);

    let (model_name, image_result) = generate_image_with_configured_default(
        &prompt_text,
        &context.image_urls,
        None,
        None,
        !CONFIG.cwd_pw_api_key.is_empty(),
        audit_context.as_ref(),
    )
    .await;

    let images = match image_result {
        Ok(images) => images,
        Err(err) => {
            error!(
                model = model_name.as_str(),
                "Image generation failed: {}", err.0
            );
            let error_text = format!(
                "Sorry, I couldn't generate the image using {}.\n\nError: {}",
                model_name, err.0
            );
            let _ = bot
                .edit_message_text(message.chat.id, processing_message.id, error_text)
                .await;
            return Ok(());
        }
    };

    let caption = build_image_caption(&model_name, &prompt_text).await;
    let mut image_iter = images.into_iter();
    if let Some(first_image) = image_iter.next() {
        let media = InputMedia::Photo(
            InputMediaPhoto::new(InputFile::memory(first_image.clone()))
                .caption(caption.clone())
                .parse_mode(ParseMode::Html),
        );
        let edit_result = bot
            .edit_message_media(message.chat.id, processing_message.id, media)
            .await;
        if edit_result.is_err() {
            bot.send_photo(message.chat.id, InputFile::memory(first_image))
                .reply_parameters(ReplyParameters::new(message.id))
                .caption(caption)
                .parse_mode(ParseMode::Html)
                .await?;
            let _ = bot
                .edit_message_text(
                    message.chat.id,
                    processing_message.id,
                    "Generated image below.",
                )
                .await;
        }
    }

    for image in image_iter {
        bot.send_photo(message.chat.id, InputFile::memory(image))
            .reply_parameters(ReplyParameters::new(message.id))
            .await?;
    }

    Ok(())
}

pub async fn img2_handler(
    bot: Bot,
    state: AppState,
    message: Message,
    _prompt: Option<String>,
) -> Result<()> {
    if !check_access_control(&bot, &message, "img2").await {
        return Ok(());
    }
    let user_id = message
        .from
        .as_ref()
        .and_then(|user| i64::try_from(user.id.0).ok())
        .unwrap_or_default();
    if is_rate_limited(user_id) {
        bot.send_message(
            message.chat.id,
            "Rate limit exceeded. Please try again later.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }

    if !crate::llm::img2_image::img2_available() {
        bot.send_message(
            message.chat.id,
            "Img2 image generation is disabled. Set ENABLE_IMG2=true and IMG2_API_KEY to enable it.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }

    let context = prepare_image_request(&bot, &state, &message, "/img2").await?;
    if context.prompt.trim().is_empty() {
        bot.send_message(message.chat.id, "Please provide a prompt for /img2.")
            .reply_parameters(ReplyParameters::new(message.id))
            .await?;
        return Ok(());
    }

    let _heavy_permit = state.acquire_heavy_command_permit().await;
    let audit_context = create_command_audit_context(&state, &message, "img2").await;

    let processing_message = bot
        .send_message(message.chat.id, "Generating your image with img2...")
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;

    let mut prompt_text = context.prompt.clone();
    if !context.telegraph_contents.is_empty() {
        prompt_text.push_str("\n\nAdditional context:\n");
        for content in &context.telegraph_contents {
            prompt_text.push_str(content);
            prompt_text.push('\n');
        }
    }

    let _chat_action =
        start_chat_action_heartbeat(bot.clone(), message.chat.id, ChatAction::UploadPhoto);
    let result = match generate_image_with_img2(
        &prompt_text,
        &context.image_urls,
        message.chat.id.0,
        message.id.0 as i64,
        audit_context.as_ref(),
    )
    .await
    {
        Ok(result) => result,
        Err(err) => {
            error!("Img2 image generation failed: {}", err.0);
            let _ = bot
                .edit_message_text(
                    message.chat.id,
                    processing_message.id,
                    format!(
                        "Sorry, I couldn't generate the image with img2.\n\nError: {}",
                        err.0
                    ),
                )
                .await;
            return Ok(());
        }
    };

    info!(
        "Sending Img2 image to Telegram: request_id={:?}, bytes={}, content_type={:?}, path={}",
        result.request_id,
        result.byte_len,
        result.content_type,
        result.path.display()
    );
    let caption = build_image_caption("img2", &prompt_text).await;
    let media = build_img2_spoiler_photo_media(InputFile::file(result.path.clone()), &caption);
    let edit_result = bot
        .edit_message_media(message.chat.id, processing_message.id, media)
        .await;
    if edit_result.is_err() {
        bot.send_photo(message.chat.id, InputFile::file(result.path.clone()))
            .reply_parameters(ReplyParameters::new(message.id))
            .caption(build_img2_spoiler_caption(&caption))
            .parse_mode(ParseMode::Html)
            .has_spoiler(true)
            .await?;
        let _ = bot
            .edit_message_text(
                message.chat.id,
                processing_message.id,
                "Generated image below.",
            )
            .await;
    }

    Ok(())
}

pub async fn image_handler(
    bot: Bot,
    state: AppState,
    message: Message,
    _prompt: Option<String>,
) -> Result<()> {
    if !check_access_control(&bot, &message, "image").await {
        return Ok(());
    }

    let user_id = message
        .from
        .as_ref()
        .and_then(|user| i64::try_from(user.id.0).ok())
        .unwrap_or_default();
    if is_rate_limited(user_id) {
        bot.send_message(
            message.chat.id,
            "Rate limit exceeded. Please try again later.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }

    let context = prepare_image_request(&bot, &state, &message, "/image").await?;
    if context.prompt.trim().is_empty() && context.image_urls.is_empty() {
        bot.send_message(
            message.chat.id,
            "Please provide a prompt or reply to an image.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }
    let audit_context = create_command_audit_context(&state, &message, "image").await;

    let gemini_available = CONFIG.gemini_api_available();
    let codex_available = crate::llm::codex_image::codex_image_available();
    if !gemini_available && !codex_available {
        bot.send_message(
            message.chat.id,
            "No image model is configured. Enable Gemini or complete Codex setup with /codexlogin.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }
    let default_image_model = match resolve_default_image_generation_model(
        &CONFIG.default_image_model,
        gemini_available,
        codex_available,
    ) {
        Ok(model) => model,
        Err(err) => {
            bot.send_message(message.chat.id, err)
                .reply_parameters(ReplyParameters::new(message.id))
                .await?;
            return Ok(());
        }
    };
    let request_key = format!("{}_{}", message.chat.id.0, message.id.0);
    let (selection_text, selection_keyboard, initial_model) = if gemini_available && codex_available
    {
        (
            "Choose an image model:".to_string(),
            build_image_model_keyboard(&request_key, true, true, default_image_model),
            None,
        )
    } else if gemini_available {
        (
            format!(
                "Choose a resolution (default: {}):",
                IMAGE_DEFAULT_RESOLUTION
            ),
            build_resolution_keyboard(&request_key),
            Some(ImageGenerationModel::Gemini),
        )
    } else {
        (
            "Choose an image size (default: Auto):".to_string(),
            build_codex_size_keyboard(&request_key),
            Some(ImageGenerationModel::CodexGptImage2),
        )
    };
    let selection_message = bot
        .send_message(message.chat.id, selection_text)
        .reply_parameters(ReplyParameters::new(message.id))
        .reply_markup(selection_keyboard)
        .await?;
    let pending = PendingImageRequest {
        user_id,
        chat_id: message.chat.id.0,
        message_id: message.id.0 as i64,
        command: PendingImageCommand::Image,
        prompt: context.prompt,
        image_urls: context.image_urls,
        telegraph_contents: context.telegraph_contents,
        selection_message_id: selection_message.id.0 as i64,
        llm_invocation_id: audit_context.as_ref().map(|context| context.invocation_id),
        model: initial_model,
        codex_size: None,
        resolution: None,
        aspect_ratio: None,
    };

    let timeout_bot = bot.clone();
    let timeout_state = state.clone();
    let timeout_key = request_key.clone();
    state.pending_image_requests.insert_with_timeout(
        request_key,
        pending,
        Duration::from_secs(CONFIG.model_selection_timeout),
        move |request| async move {
            let should_finalize = match request.model {
                None => true,
                Some(ImageGenerationModel::Gemini) => request.resolution.is_none(),
                Some(ImageGenerationModel::CodexGptImage2) => request.codex_size.is_none(),
            };
            if should_finalize {
                let _ = finalize_image_request(
                    &timeout_bot,
                    &timeout_state,
                    request,
                    Some(IMAGE_DEFAULT_RESOLUTION),
                    None,
                )
                .await;
            } else {
                // The user already picked a resolution and is choosing an
                // aspect ratio; keep waiting for that click (no deadline, as
                // before).
                timeout_state
                    .pending_image_requests
                    .insert(timeout_key, request);
            }
        },
    );

    Ok(())
}

pub async fn vid_handler(
    bot: Bot,
    state: AppState,
    message: Message,
    prompt: Option<String>,
) -> Result<()> {
    if !check_access_control(&bot, &message, "vid").await {
        return Ok(());
    }
    if !CONFIG.gemini_api_available() {
        bot.send_message(
            message.chat.id,
            "The /vid command requires Gemini and is disabled.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }

    let user_id = message
        .from
        .as_ref()
        .and_then(|user| i64::try_from(user.id.0).ok())
        .unwrap_or_default();
    if is_rate_limited(user_id) {
        bot.send_message(
            message.chat.id,
            "Rate limit exceeded. Please try again later.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }

    let reply_has_image = message
        .reply_to_message()
        .map(message_has_image)
        .unwrap_or(false);
    if message_has_image(&message) || reply_has_image {
        send_message_with_retry(
            &bot,
            message.chat.id,
            "Image input isn't supported for /vid right now. Please send a text-only prompt.\nUsage: /vid [text prompt]",
            Some(message.id),
        )
        .await?;
        return Ok(());
    }

    let original_message_text = message
        .text()
        .map(|value| value.to_string())
        .or_else(|| message.caption().map(|value| value.to_string()))
        .unwrap_or_default();

    let prompt_text =
        prompt.unwrap_or_else(|| strip_command_prefix(&original_message_text, "/vid"));
    if prompt_text.trim().is_empty() {
        bot.send_message(
            message.chat.id,
            "Please provide a prompt for the video.\nUsage: /vid [text prompt]",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }
    let _heavy_permit = state.acquire_heavy_command_permit().await;
    let audit_context = create_command_audit_context(&state, &message, "vid").await;

    let processing_message = send_message_with_retry(
        &bot,
        message.chat.id,
        "Processing video request... This may take a few minutes.",
        Some(message.id),
    )
    .await?;
    let _chat_action =
        start_chat_action_heartbeat(bot.clone(), message.chat.id, ChatAction::Typing);
    let (video_bytes, _mime_type) =
        generate_video_with_veo(&prompt_text, audit_context.as_ref()).await?;

    if let Some(video_bytes) = video_bytes {
        send_video_with_retry(&bot, message.chat.id, &video_bytes, Some(message.id)).await?;
    } else {
        edit_message_text_with_retry(
            &bot,
            message.chat.id,
            processing_message.id,
            "Video generation is unavailable right now.",
        )
        .await?;
    }

    Ok(())
}

/// Legacy single-call /tldr: the whole history in one prompt. Used below the
/// map-reduce threshold and as the fallback when the pipeline cannot start.
async fn tldr_single_call(
    messages: &[crate::db::models::MessageRow],
    audit_context: Option<&LlmAuditContext>,
) -> Result<(String, String)> {
    let chat_content = crate::llm::prompting::wrap_chat_history(
        &crate::llm::prompting::format_tldr_chat_content(messages),
    );
    let system_prompt = TLDR_SYSTEM_PROMPT.replace("{bot_name}", &CONFIG.telegraph_author_name);
    call_configured_text_model(
        &system_prompt,
        &chat_content,
        "Message Summary",
        true,
        true,
        None,
        Some("TLDR_SYSTEM_PROMPT"),
        audit_context,
    )
    .await
}

const TLDR_DEFAULT_MESSAGE_COUNT: i64 = 100;

/// Number of messages `/tldr <n>` should summarize, clamped to a sane range so
/// a negative or huge argument cannot turn into an unbounded fetch.
fn resolve_tldr_count(arg: Option<&str>, max_messages: usize) -> i64 {
    let max = i64::try_from(max_messages).unwrap_or(i64::MAX).max(1);
    arg.and_then(|value| value.trim().parse::<i64>().ok())
        .unwrap_or(TLDR_DEFAULT_MESSAGE_COUNT)
        .clamp(1, max)
}

pub async fn tldr_handler(
    bot: Bot,
    state: AppState,
    message: Message,
    count: Option<String>,
) -> Result<()> {
    if !check_access_control(&bot, &message, "tldr").await {
        return Ok(());
    }

    let user_id = message
        .from
        .as_ref()
        .and_then(|user| i64::try_from(user.id.0).ok())
        .unwrap_or_default();
    if is_rate_limited(user_id) {
        bot.send_message(
            message.chat.id,
            "Rate limit exceeded. Please try again later.",
        )
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
        return Ok(());
    }
    let _heavy_permit = state.acquire_heavy_command_permit().await;

    let mut timer = start_command_timer("tldr", &message);
    let processing_message = bot
        .send_message(message.chat.id, "Summarizing recent messages...")
        .reply_parameters(ReplyParameters::new(message.id))
        .await?;
    let _chat_action =
        start_chat_action_heartbeat(bot.clone(), message.chat.id, ChatAction::Typing);

    let mut messages = if let Some(reply) = message.reply_to_message() {
        // Fetch one past the cap so the truncation notice below still fires
        // without pulling the whole chat into memory.
        let fetch_limit = (CONFIG.tldr_max_messages + 1) as i64;
        state
            .db
            .select_messages_from_id(message.chat.id.0, reply.id.0 as i64, fetch_limit)
            .await?
    } else {
        let n = resolve_tldr_count(count.as_deref(), CONFIG.tldr_max_messages);
        state.db.select_messages(message.chat.id.0, n).await?
    };

    if messages.is_empty() {
        bot.edit_message_text(
            message.chat.id,
            processing_message.id,
            "No messages found to summarize.",
        )
        .await?;
        complete_command_timer(&mut timer, "error", Some("no_messages".to_string()));
        return Ok(());
    }

    // The reply-anchored fetch has no LIMIT; cap it, keeping the newest
    // messages, so a reply to an ancient message cannot pull the whole table.
    let truncated_to_cap = messages.len() > CONFIG.tldr_max_messages;
    if truncated_to_cap {
        let skip = messages.len() - CONFIG.tldr_max_messages;
        messages.drain(..skip);
    }
    let audit_context = create_command_audit_context(&state, &message, "tldr").await;

    let summary_result = if messages.len() > CONFIG.tldr_map_reduce_threshold {
        let mut progress_reporter =
            ProgressReporter::new(bot.clone(), message.chat.id, processing_message.id);
        match crate::agents::tldr::summarize_messages_map_reduce(
            &messages,
            audit_context.as_ref(),
            &mut progress_reporter,
        )
        .await
        {
            Ok(crate::agents::tldr::TldrOutcome::Summary {
                text,
                model_display,
            }) => Ok((text, model_display)),
            Ok(crate::agents::tldr::TldrOutcome::UseLegacy { reason }) => {
                info!("Map-reduce /tldr fell back to the single-call path: {reason}");
                tldr_single_call(&messages, audit_context.as_ref()).await
            }
            Err(err) => Err(err),
        }
    } else {
        tldr_single_call(&messages, audit_context.as_ref()).await
    };

    let response = match summary_result {
        Ok(response) => response,
        Err(err) => {
            error!("TLDR summary generation failed: {}", err);
            bot.edit_message_text(
                processing_message.chat.id,
                processing_message.id,
                format!("Failed to generate a summary.\n\nError: {}", err),
            )
            .await?;
            complete_command_timer(
                &mut timer,
                "error",
                Some("summary_generation_failed".to_string()),
            );
            return Ok(());
        }
    };

    let (mut summary_text, summary_model) = response;
    if truncated_to_cap {
        summary_text = format!(
            "（注：消息数量超过上限，本次仅总结最近 {} 条消息。）\n\n{}",
            CONFIG.tldr_max_messages, summary_text
        );
    }
    if summary_text.trim().is_empty() {
        bot.edit_message_text(
            processing_message.chat.id,
            processing_message.id,
            "Failed to generate a summary. Please try again later.",
        )
        .await?;
        complete_command_timer(&mut timer, "error", Some("empty_summary".to_string()));
        return Ok(());
    }

    let model_line = format!("Model: {}", escape_html(&summary_model));
    let summary_with_model = format!(
        "{}\n\n{}",
        markdown_to_telegram_html(&summary_text),
        model_line
    );
    let infographic_enabled = CONFIG.enable_tldr_infographic;

    let _ = bot
        .edit_message_text(
            processing_message.chat.id,
            processing_message.id,
            if infographic_enabled {
                "Summary generated. Generating infographic..."
            } else {
                "Summary generated. Skipping infographic step..."
            },
        )
        .await;

    let infographic_prompt = format!(
        "Create a clear infographic (no walls of text) summarizing the key points below. \
Use a 16:9 layout with readable labels and visual hierarchy suitable for Telegram. \
Use the same language as the summary text for any labels.\
\n\n{}",
        summary_text
    );

    let mut infographic_url = None;
    if infographic_enabled {
        let infographic_config = Some(GeminiImageConfig {
            aspect_ratio: Some("16:9".to_string()),
            image_size: Some("4K".to_string()),
        });
        let (infographic_model, infographic_result) = generate_image_with_configured_default(
            &infographic_prompt,
            &[],
            infographic_config,
            None,
            false,
            audit_context.as_ref(),
        )
        .await;
        match infographic_result {
            Ok(images) => {
                if let Some(image) = images.into_iter().next() {
                    if CONFIG.cwd_pw_api_key.trim().is_empty() {
                        warn!("TLDR infographic generated but CWD_PW_API_KEY is not configured.");
                    } else {
                        let mime_type =
                            detect_mime_type(&image).unwrap_or_else(|| "image/png".to_string());
                        infographic_url = upload_image_bytes_to_cwd(
                            &image,
                            &CONFIG.cwd_pw_api_key,
                            &mime_type,
                            Some(infographic_model.as_str()),
                            Some(&infographic_prompt),
                        )
                        .await;
                        if infographic_url.is_none() {
                            warn!("Failed to upload TLDR infographic to cwd.pw.");
                        }
                    }
                } else {
                    warn!("TLDR infographic generation returned no image.");
                }
            }
            Err(err) => {
                error!("Error generating TLDR infographic: {}", err);
            }
        }
    }

    let mut telegraph_url = None;
    if let Some(url) = &infographic_url {
        let telegraph_content = format!(
            "![Infographic]({})\n\n{}\n\nModel: {}",
            url, summary_text, summary_model
        );
        telegraph_url =
            create_telegraph_page("Message Summary with Infographic", &telegraph_content).await;
    }

    let final_message = if let Some(url) = telegraph_url {
        format!(
            "Chat summary with infographic: <a href=\"{}\">View it here</a>\n\n{}",
            escape_html(&url),
            model_line
        )
    } else if let Some(url) = infographic_url {
        format!(
            "{}\n\nInfographic: <a href=\"{}\">View it here</a>",
            summary_with_model,
            escape_html(&url)
        )
    } else {
        summary_with_model
    };

    let _ = bot
        .edit_message_text(
            processing_message.chat.id,
            processing_message.id,
            if infographic_enabled {
                "Infographic step completed. Finalizing response..."
            } else {
                "Finalizing response..."
            },
        )
        .await;

    send_response(
        &bot,
        processing_message.chat.id,
        processing_message.id,
        &final_message,
        "Message Summary",
        ParseMode::Html,
    )
    .await?;
    complete_command_timer(&mut timer, "success", None);

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_image_model_accepts_gemini_and_codex_aliases() {
        assert_eq!(
            parse_default_image_generation_model("gemini"),
            Some(ImageGenerationModel::Gemini)
        );
        assert_eq!(
            parse_default_image_generation_model("codex"),
            Some(ImageGenerationModel::CodexGptImage2)
        );
        assert_eq!(
            parse_default_image_generation_model("openai-codex"),
            Some(ImageGenerationModel::CodexGptImage2)
        );
        assert_eq!(
            parse_default_image_generation_model("openai-codex:selected"),
            Some(ImageGenerationModel::CodexGptImage2)
        );
    }

    #[test]
    fn default_image_model_rejects_unknown_values() {
        assert_eq!(parse_default_image_generation_model("openrouter:gpt"), None);
        assert_eq!(parse_default_image_generation_model(""), None);
    }

    #[test]
    fn default_image_model_errors_when_codex_unavailable() {
        let result = resolve_default_image_generation_model("codex", true, false);

        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .contains("Default image model codex is unavailable"));
    }

    #[test]
    fn default_image_model_accepts_available_codex() {
        assert_eq!(
            resolve_default_image_generation_model("codex", true, true),
            Ok(ImageGenerationModel::CodexGptImage2)
        );
    }

    #[test]
    fn default_image_model_uses_codex_when_gemini_disabled() {
        assert_eq!(
            resolve_default_image_generation_model("gemini", false, true),
            Ok(ImageGenerationModel::CodexGptImage2)
        );
    }

    #[test]
    fn resolve_image_request_settings_prefers_saved_resolution_and_aspect_ratio() {
        let request = PendingImageRequest {
            user_id: 1,
            chat_id: 2,
            message_id: 3,
            command: PendingImageCommand::Image,
            prompt: "test".to_string(),
            image_urls: Vec::new(),
            telegraph_contents: Vec::new(),
            selection_message_id: 4,
            llm_invocation_id: None,
            model: Some(ImageGenerationModel::Gemini),
            codex_size: None,
            resolution: Some("4K".to_string()),
            aspect_ratio: Some("16:9".to_string()),
        };

        let (final_resolution, final_aspect) =
            resolve_image_request_settings(&request, None, Some("1:1"));

        assert_eq!(final_resolution, "4K");
        assert_eq!(final_aspect.as_deref(), Some("1:1"));
    }

    #[test]
    fn resolve_image_request_settings_omits_default_aspect_ratio() {
        let request = PendingImageRequest {
            user_id: 1,
            chat_id: 2,
            message_id: 3,
            command: PendingImageCommand::Image,
            prompt: "test".to_string(),
            image_urls: Vec::new(),
            telegraph_contents: Vec::new(),
            selection_message_id: 4,
            llm_invocation_id: None,
            model: Some(ImageGenerationModel::Gemini),
            codex_size: None,
            resolution: None,
            aspect_ratio: None,
        };

        let (final_resolution, final_aspect) =
            resolve_image_request_settings(&request, Some("2K"), None);

        assert_eq!(final_resolution, "2K");
        assert_eq!(final_aspect, None);
    }

    #[test]
    fn img2_caption_is_wrapped_in_html_spoiler() {
        assert_eq!(
            build_img2_spoiler_caption("Generated by img2"),
            "<tg-spoiler>Generated by img2</tg-spoiler>"
        );
    }

    #[test]
    fn img2_photo_media_uses_spoiler_flag_and_spoiler_caption() {
        let media = build_img2_spoiler_photo_media(InputFile::file("img2.png"), "caption");

        let InputMedia::Photo(photo) = media else {
            panic!("img2 should use photo media");
        };
        assert!(photo.has_spoiler);
        assert_eq!(
            photo.caption.as_deref(),
            Some("<tg-spoiler>caption</tg-spoiler>")
        );
        assert_eq!(photo.parse_mode, Some(ParseMode::Html));
    }

    #[test]
    fn image_model_callback_data_round_trips_known_models() {
        assert_eq!(
            image_model_callback_data("chat_msg", ImageGenerationModel::Gemini),
            "image_model:chat_msg|gemini"
        );
        assert_eq!(
            image_model_callback_data("chat_msg", ImageGenerationModel::CodexGptImage2),
            "image_model:chat_msg|codex"
        );
        assert_eq!(
            parse_image_generation_model("gemini"),
            Some(ImageGenerationModel::Gemini)
        );
        assert_eq!(
            parse_image_generation_model("codex"),
            Some(ImageGenerationModel::CodexGptImage2)
        );
        assert_eq!(parse_image_generation_model("unknown"), None);
    }

    #[test]
    fn image_model_keyboard_puts_default_model_first() {
        let keyboard =
            build_image_model_keyboard("req", true, true, ImageGenerationModel::CodexGptImage2);
        let rows = keyboard.inline_keyboard;
        let callbacks = rows
            .iter()
            .flatten()
            .filter_map(|button| match &button.kind {
                teloxide::types::InlineKeyboardButtonKind::CallbackData(value) => {
                    Some(value.as_str())
                }
                _ => None,
            })
            .collect::<Vec<_>>();

        assert_eq!(callbacks.first().copied(), Some("image_model:req|codex"));
    }

    #[test]
    fn codex_size_keyboard_uses_supported_size_callbacks() {
        let markup = build_codex_size_keyboard("req");
        let rows = markup.inline_keyboard;
        let labels = rows
            .iter()
            .flat_map(|row| row.iter().map(|button| button.text.clone()))
            .collect::<Vec<_>>();

        assert_eq!(
            labels,
            vec![
                "1024x1024",
                "1536x1024",
                "1024x1536",
                "2048x2048",
                "2048x1152",
                "3840x2160",
                "2160x3840",
            ]
        );
        assert_eq!(
            match &rows[0][0].kind {
                teloxide::types::InlineKeyboardButtonKind::CallbackData(value) =>
                    Some(value.as_str()),
                _ => None,
            },
            Some("image_codex_size:req|1024x1024")
        );
    }

    #[test]
    fn tldr_count_defaults_when_missing_or_unparsable() {
        assert_eq!(resolve_tldr_count(None, 2_000), TLDR_DEFAULT_MESSAGE_COUNT);
        assert_eq!(
            resolve_tldr_count(Some("lots"), 2_000),
            TLDR_DEFAULT_MESSAGE_COUNT
        );
        assert_eq!(resolve_tldr_count(Some(" 50 "), 2_000), 50);
    }

    #[test]
    fn tldr_count_is_clamped_to_a_bounded_range() {
        assert_eq!(resolve_tldr_count(Some("-1"), 2_000), 1);
        assert_eq!(resolve_tldr_count(Some("0"), 2_000), 1);
        assert_eq!(resolve_tldr_count(Some("9999999"), 2_000), 2_000);
    }
}
